title: "Chun-chieh (John) Tseng"
description: "Full-Stack Data Analyst | Python · SQL · Machine Learning"
email: zengjunjie5856@gmail.com
github_username: ghjohntseng
linkedin_username: chunchieh-t
location: "Toronto / New York"
resume: "https://www.dropbox.com/scl/fi/your-resume-link.pdf"

